### PR TITLE
Create tokyojs.svg

### PR DESCRIPTION
**Pull request by Hypercubed**
Perhaps the font is not exactly right...

### CODE REVIEW

**Comment by bucaran** [comment]
[Futura LT Bold.txt](https://github.com/tokyojs/logo/files/62127/Futura.LT.Bold.txt)

@Hypercubed Here is the font (Futura LT Bold) attached. Just change the `.txt` to `.ttf`. 

Would you mind changing that for me?

**Comment by Hypercubed** [comment]
Done, although it's probably dependent on the users machine.  The only way to ensure consistency may be to convert the text to a path.

**Comment by Hypercubed** [comment]
If you prefer we can use this one.  https://github.com/Hypercubed/logo/blob/text-to-path/tokyojs.svg  It's obviously bigger.

**Comment by bucaran** [comment]
Perhaps converting to a path is better. BTW are you using Illustrator?

**Comment by Hypercubed** [comment]
Nope, doing it by hand. :smile:

**Comment by bucaran** [comment]
@Hypercubed I'm so thankful, but I really need to have the logo look exactly the same as the current one. See the attached screenshot.

screen shot 2015-12-15 at 5 06 23 pm

**Comment by bucaran** [comment]
@Hypercubed Please disregard my previous lame comment. I can totally edit those bits in the SVG myself :sweat_smile:

**Comment by Hypercubed** [comment]
Yeah, sorry.  I wasn't trying to reproduce exactly.

**Pull request merged**
